//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindforkBlog.Infrastructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long CommentId { get; set; }
        public long BlogId { get; set; }
        public long UserId { get; set; }
        public string CommentContent { get; set; }
        public Nullable<long> CommentLike { get; set; }
        public Nullable<long> CommentDislike { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
    }
}
